#!/bin/bash

if [[ $# -ne 4 ]]; then
	exit 1
fi

input_file="$1"

if [[ ! -f input_file ]]; then
	exit 1
fi

output_file="$2"
object="$3"
member="$4"

value=$(jq -r ".${object}.${member}" "${input_file}")

if [[ "$value" = "null" ]]; then
	exit 1
fi

echo "${value}" > "${output_file}"

exit 0
